### ISSUE TITLE
日历白屏

### ISSUE THREAD

**Issue by QianFuv** [kongxiangyiren/vercel-githubcalendar#1]
![chrome_4iQros4a4M](https://github.com/kongxiangyiren/vercel-githubcalendar/assets/111696321/c591bdff-be4e-4f3a-8950-b581e1d8b9fe)
测试地址：https://blog.qianf.fun/
控制台报错：TypeError: Cannot read properties of undefined (reading 'length')  at gitcalendar.js:202:41

**Comment by QianFuv** [comment]
配置文件：
```
gitcalendar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  # butterfly挂载容器
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  # volantis挂载容器
  # layout:
  #   type: class
  #   name: l_main
  #   index: 0
  # matery挂载容器
  # layout:
  #   type: id
  #   name: indexCard
  #   index: 0
  # mengd挂载容器
  # layout:
  #   type: class
  #   name: content
  #   index: 0
  user: Qian-F #git用户名
  apiurl: https://gitcalenderapi.qianf.fun/api/githubcalendar
  minheight:
    pc: 280px #桌面端最小高度
    mibile: 0px #移动端最小高度
  #color: "['#e4dfd7', '#f9f4dc', '#f7e8aa', '#f7e8aa', '#f8df72', '#fcd217', '#fcc515', '#f28e16', '#fb8b05', '#d85916', '#f43e06']" #橘黄色调
  color: "['#E6E6E6', '#CFCFCF', '#B8B8B8', '#A1A1A1', '#8A8A8A', '#737373', '#5C5C5C', '#454545', '#2E2E2E', '#171717', '#000000']" #浅紫色调
  # color: "['#ebedf0', '#f0fff4', '#dcffe4', '#bef5cb', '#85e89d', '#34d058', '#28a745', '#22863a', '#176f2c', '#165c26', '#144620']" #翠绿色调
  # color: "['#ebedf0', '#f1f8ff', '#dbedff', '#c8e1ff', '#79b8ff', '#2188ff', '#0366d6', '#005cc5', '#044289', '#032f62', '#05264c']" #天青色调
  container: .recent-post-item(style='width:100%;height:auto;padding:10px;') #父元素容器，需要使用pug语法
  gitcalendar_css: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.css
  gitcalendar_js: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.js
```
